
meta_product_name: "OG Stoneheads"
meta_title: "OG Stoneheads - 2420 NFT's Puffing on Solana Blockchain"
meta_description: "2420 Unique Stoneheads chillin’ on the #Solana blockchain | Powered by $KIEF🌿|"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@OG_Stoneheads"   # required for Twitter Cards
